version: '2.1'
services:
  redis-docker:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: always
    container_name: redis-docker
    volumes:
      - redis_data:/data
    networks:
      - redis-network
volumes:
  redis_data:

networks:
  redis-network:
